// <auto-generated />
using System;
using ChocolateFactoryApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChocolateFactoryApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChocolateFactoryApi.Models.ProductionSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("int");

                    b.HasKey("ScheduleId");

                    b.ToTable("ProductionSchedules");
                });

            modelBuilder.Entity("ChocolateFactoryApi.Models.RawMaterial", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialId"));

                    b.Property<decimal>("CostPerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int>("SuppilerId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaterialId");

                    b.ToTable("RawMaterials");
                });

            modelBuilder.Entity("ChocolateFactoryApi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "Manager@factory.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$cgIIqNPh6ueOB.L.lWPKv.0mXC5fIC4yAGq0L1sRzVrZUbx5cs97u",
                            Role = "FactorManager",
                            UserName = "Manager"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "Quality@factory.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$Xgyzjmax5BeNatMlex74Xuiyeo9B/m/xxZ3mFFCipORvQE3JuLv4S",
                            Role = "QualityController",
                            UserName = "quality"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "supervisor@factory.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$F25ylK0PsWcn0teYn17B6eVr4cylSXyy0txjJ8/UZHFXraPXwyMwS",
                            Role = "ProductionSupervisor",
                            UserName = "supervisor"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "warehouse@factory.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$uJhN5VF/O1s5/z5tgrfEtOq9W.JuVpOo73hjnFkrPTTprLdzIDI46",
                            Role = "warehouseStaff",
                            UserName = "warehouse"
                        },
                        new
                        {
                            UserId = 5,
                            Email = "sales@factory.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$7X.3U4wgVpL3WD8dMYD6DOOKeZZlLvtaZImjboEKEmOEV2Dj1iP82",
                            Role = "SalesRepresentative",
                            UserName = "sales"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
